# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 윤 성 철
title: Developer
email: sungchul05.dev@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: sungchulyun

# Additional icon links
additional_links:
- title: sung_c.velog
  icon: fas fa-globe
  url: velog.io/@sung_c/posts
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  안녕하세요, 3년차 개발자 윤성철입니다.
  
  총 3번의 금융 도메인 프로젝트에서 2번의 은행권 프로젝트 경험을 했습니다. 특히, 은행 내부 배치와 DM, DW 프로세스를 몸소 겪으며 <mark>화면 개발</mark>, 
  <mark>ETL 개발을 통한 데이터 이행</mark> 등 다양한 업무를 수행했습니다. 
  
  또한, 사내 솔루션 유지보수, 신사업 poc 업무를 수행하면서 문서화하고 공유하는 과정을 통해 팀 생산성 향상에 꾸준히 기여하고 있습니다. 
  특히. 메일 서버 구축, CI/CD 환경 구축, Linux OS 설치 등 수행 과정에서의 트러블 슈팅 가이드를 작성하여 공유했습니다.
  
  LLM 모델을 사용하여 생산성 향상을 높이는 방안을 지속적으로 고민합니다. 
  작성된 코드 검증과 사고력 증진을 위해 주 5문제 이상 알고리즘 문제를 풀며 단련하고 있습니다.
  <br>

content:
  #경력
  - title: Career
    layout: list
    content:
      - layout: left
        title: (주)아이티아이즈
        sub_title: 금융사업본부 솔루션사업팀
        caption: 2024.01 ~ 현재
        quote: >
          연매출 600억의 금융 SI 기업
        description: |
          
          **EDW 재구축 프로젝트(2025.03 ~ 10)**
          
            기술 스택 : `Oracle`, `TeraStream`, `MariaDB`, `Linux`
          
            업무 : 데이터 이행
          
            주요 성과 : 
            - 총 20TB, 200여 개의 테이블 데이터 이행

          <br>
          
          **우리은행 IFRS 재무회계시스템 노후 인프라 교체 프로젝트(2024.07 ~ 09)**
          
            기술 스택 : `NEXACRO`, `SpringBoot`, `MyBatis`, `Oracle`        
          
            업무 : 공시, 지분투자 등 보고서 화면 개발
          
            주요 성과 :
            - AS-IS의 30개의 보고서 파일을 TO-BE 전환 작업에서 7개로 간소화 
          
          <br>
          
          **조각투자 플랫폼 블록체인 연계 API 개발 (2024.04 ~ 2024.06)**
          
            기술 스택 : `Java17`, `SpringBoot`, `MyBatis`, `MariaDB`    
          
            업무 : 토큰 지갑 생성, 조회, 폐기 및 토큰 배정 API 개발
          
           주요 성과 :
            - 단건 INSERT, UPDATE 쿼리를 Bulk 전환으로 17.04초 -> 6.20초로 성능 개선
            - 기존 로직에서 트랜잭션 처리와 외부 API 요청을 분리하여 데이터 정합성 강화
            - 외부 API 호출 간 RestTemplate에서 feign-Client 전환으로 7.04초 -> 3.8초로 성능 개선 
            
          <br>
          
  - title: Skill
    layout: list
    content:
      - layout: left
        title: Backend
        sub_title:
        description: |
          - Java, Javascript
          - Spring Boot, Spring Security, Redis
          - JPA, QueryDSL, Mybatis
          - Gradle, Maven
          - IntelliJ, Eclipse
      - layout: left
        title: DevOps
        sub_title:
        description: |
          - MySQL, MariaDB, Oracle
          - AWS RDS, EC2, S3
          - Nginx, Tomcat
          - Linux, Centos
  #프로젝트
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Daily-Mission
        caption: 2024.05 ~ 2024.12
        link: https://github.com/sungchulyun/Daily-mission_BE
        link_text: https://github.com/sungchulyun/Daily-mission_BE
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: https://github.com/sungchulyun/Daily-mission_BE
        quote: >
          일일 미션 인증 프로젝트 <br>
        description: | 
          
          기술 스택 :
          - Backend : `Java`, `SpringBoot`, `Spring Security`, `Spring Data JPA`, `Spring Batch`
          - DB : `AWS RDS(MariaDB)`, `QueryDSL`, `Redis`
          - Infra : `Docker`, `Github-Action`, `AWS EC2`, `AWS S3`, `AWS ROUTE 53`
          <br>
        
          개발 내용 :
          - OAuth2, JWT, Spring Security를 활용한 인증, 인가 개발
          - Spring Batch와 Scheduler를 사용하여 미션 종료 및 강제 퇴장 기능 구현
          - AWS S3 & PresignedUrl을 통한 파일 업로드 기능 구현
          - SSE & Redis pub/sub 실시간 푸시 알림 기능 구현
          
          주요 경험 : 
          - PER 알고리즘 적용을 통해 평균 1800TPS -> 2400TPS 성능 향상 및 캐시 스탬피드 현상 완화 
          - 비관적 락을 통한 동시성 이슈 해결
          - AWS Route53 & AWS IAM(SSL)를 통한 백엔드 인프라 구축
          - Junit & Mockito를 활용한 단위 테스트 작성
          - Test Container를 사용한 통합 테스트 수행
#교육
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: 삼육대학교
        sub_title: 컴퓨터메카트로닉스 공학 전공
        caption: 2016.03 - 2023.02
        description: |
          
          학점 : 3.69 / 4.5
          
          성적 우수 장학금 3회 및 성적 향상 장학금 수혜

  #수상
  - title: Awards # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: 삼육대학교 SW 프로젝트 경진대회
        sub_title: 최우수상
        caption: 2022.09.27
        quote: >
          저소득층 아동, 청소년을 위한 영양 개선 프로젝트
        description: |
          - 식품영양 공공데이터를 활용한 식단 기록, 조회 API 개발

      - layout: top-left
        title: 한이음 ICT 프로보노 공모전
        sub_title: 동상 (한국정보방송통신대연합회장상)
        caption: 2021.12.02
        quote: >
          객체 인식을 활용한 시각장애인용 지하철 내비게이션
        description: |
          - 지하철 공공데이터를 활용한 지하철 도착 정보 및 경로 안내 API 개발
          - Kakao OCR API를 사용하여 이정표 정보를 추출하는 기능 구현

      - layout: top-left
        title: 삼육대학교 창업오디션 Su-StartUp
        sub_title: 최우수상
        caption: 2021.12.01
        quote : >
          시각장애인용 지하철 네비게이션 사업화 아이디어
        description: |
          - 시각장애인용 지하철 내비게이션 사업계획서 작성 및 발표


#자격 사항
  - title: Certificate # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: list
        title: 정보처리기사
        caption: 2023.06.09
          <br>
#어학
  - title: 공인영어 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: list
        title: 토익 850
        caption: 2026.02.08
          <br>

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]